name: open_workshop19
channels:
  - bokeh
  - conda-forge
  - defaults
dependencies:
  - bokeh=1.3.4
  - cartopy=0.17.0
  - colorcet=2.0.1
  - descartes=1.1.0 
  - faker=2.0.1
  - geopandas=0.5.1
  - geoviews=1.6.3
  - geoviews-core=1.6.3
  - holoviews=1.12.5
  - hvplot=0.4.0
  - ipython
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - numpy=1.15.4
  - pandas=0.25.1
  - python=3.7
  - scipy=1.3.1
  - seaborn=0.9.0
 